---
- set_fact:
    apt_packages: "{{ __apt_packages|list }}"
  when: apt_packages|default(None) == None

- name: Cleanup role default variables
  set_fact:
    __apt_packages: !!null

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-dev-freetz"
     package_depends: "{{ apt_packages }}"

- set_fact:
    apt_packages: !!null
